### PR TITLE
Add index to refreshtoken model

### PR DESCRIPTION
**Pull request by pjbollinger**
This should fix the `ValueError: Found wrong number (0) of constraints for oauth2_provider_refreshtoken(application_id, user_id)` error that occurs when running `migrate` or `makemigrations` on the previous commit. There was a mismatch between the model and the migration manually created.

I'm not sure if this will accomplish what @MicGong was trying to achieve in #3, so please review.

Feel free to add anybody else appropriate for review.

I should note that I did try to just run `makemigration` with the model change, but the error still came up, which is why I decided to remove the previous migration and replace it with this migration.

### CODE REVIEW

**Review by AlecRosenbaum — COMMENTED** [review]
LGTM, but lets see what @MicGong thinks

**Review by MicGong — CHANGES_REQUESTED** [review]
I don't think it's a good idea to delete already applied migration files. Probably it's better keep it as is and have a new migration instead. This way the migration history will be preserved.

**Comment by pjbollinger** [comment]
I agree that modifying applied migration files is not good. However, I'm not sure the migration from #3 is actually applied when ran. It records it in the `django_migrations` table but always produces an error when running it. Also, I can't seem to create a new migration (0006) until the old 0005 is removed. I'm open to suggestions on how to handle it, but I'm not sure the best way is.

**Review by MicGong — APPROVED** [review]

**Comment by pjbollinger** [comment]
Just as a follow up, talked with Jian off GitHub and did some testing. He tested it on his machine that had a fix to the DB already and I tested on mine that migrated from 0004. Both cases worked out OK, so it shouldn't have issues deploying.

**Pull request merged**
